user/models.py
from application import db
from utilities.common import utc_now_ts as now


class User(db.Document):
    username = db.StringField(db_field="u", required=True, unique=True)
    password = db.StringField(db_field="p", required=True)
    email = db.StringField(db_field="e", required=True,unique=True)
    first_name = db.StringField(db_field="fn", max_length=50)
    last_name = db.StringField(db_field="ln", max_length=50)
    created = db.IntField(db_field="c", default=now())
    bio=db.StringField(db_field="b",max_length=50)

    meta={
          'indexes':['username','email','-created'],
          #"db_alias":"booksservice","alias":"default"
    }

user/forms.py
from flask_wtf import Form
from wtforms import validators, StringField, PasswordField
from wtforms.fields.html5 import EmailField
from wtforms.validators import ValidationError

from user.models import User


class RegisterForm(Form):
    first_name = StringField('First Name', [validators.DataRequired()])
    last_name = StringField('Last Name', [validators.DataRequired()])
    email = EmailField('Email Address', [
                       validators.DataRequired(), validators.Email()])
    username = StringField(
        'Username', [validators.DataRequired(), validators.length(min=4, max=25)])
    password = PasswordField('New Password', [validators.DataRequired(), validators.EqualTo(
        'confirm', message='Passwords must match'), validators.length(min=4, max=80)])
    confirm = PasswordField('Repeat Password')

    def validate_username(form, field):  # custom validator
        if User.objects.filter(username=field.data).first():
            raise ValidationError('Username already exists.')

    def validate_email(form, field):
        if User.objects.filter(email=field.data).first():
            raise ValidationError("Email already in use.")

class LoginForm(Form):
    username = StringField(
        'Username', [validators.DataRequired(), validators.length(min=4, max=25)])
    password = PasswordField('Password', [validators.DataRequired(),  validators.length(min=4, max=80)])

user/views.py
from flask import Blueprint, render_template,request,redirect,session,url_for
from user.forms import RegisterForm, LoginForm
import bcrypt
from user.models import User

user_app = Blueprint('user_app', __name__)  # naming the app


@user_app.route('/login', methods=["GET", "POST"])
def login():
    form=LoginForm()
    error=None

    if form.validate_on_submit():
        user=User.objects.filter(
            username=form.username.data
        ).first()
        if user:#user found
            if bcrypt.hashpw(form.password.data,user.password)==user.password:
                print("2")
                session['username']=form.username.data
                return 'User logged in'
            else:
                user =None
        if not user:#password is incorrent
            error='Incorrect credentials'
    return render_template('user/login.html',form=form,error=error)


@user_app.route('/register', methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(form.password.data, salt)
        user = User(username=form.username.data,
                    password=hashed_password,
                    email=form.email.data,
                    first_name=form.first_name.data,
                    last_name=form.last_name.data)
        user.save()
        return "User registered"
    return render_template('user/register.html', form=form)

@user_app.route('/logout', methods=["GET", "POST"])
def logout():
    session.pop('username')
    return redirect(url_for('user_app.login'))

@user_app.route('/<username>', methods=["GET", "POST"])
def profile(username):
    user=User.objects.filter(username=username).first()
    return render_template('user/profile.html',user=user)

templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }} {{ field(**kwargs)|safe }} {% if field.errors %}
  <ul class="text-danger">
    {% for error in field.errors %}
    <li>{{ error }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>
{% endmacro%}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"> {% block header %}
  {% endblock %}

</head>

<body>

  <div class="container">

    {% block content %}{% endblock %}

    <div class="col-md-offset-3 col-md-6">
      <hr />
      <footer>
        &copy; copyright 2016 flaskbook
      </footer>
    </div>

  </div>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://code.jquery.com/jquery-1.12.1.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> {% block end_body_js %} {%
  endblock %}

</body>

</html>

templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img alt="flaskbook logo" width="82" height="20" src="{{ url_for('static', filename='assets/flaskbook-logo-sm.png') }}">
      </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        {% if session.username %}
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            @{{ session.username }} <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#">View Profile</a></li>
            <li><a href="#">Edit Profile</a></li>
            <li><a href="#">Change Password</a></li>
          </ul>
        </li>
        <li>
          <a href="{{ url_for('user_app.logout') }}" class="navbar-link">Logout</a></p>
        </li>
        {% else %}
        <li>
          <a href="{{ url_for('user_app.login') }}" class="navbar-link">Login</a></p>
        </li>
        <li>
          <a href="{{ url_for('user_app.register') }}" class="navbar-link">Register</a></p>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/user/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content %} {% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>User Login</h3>

    {% if error %}
    <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endif %} {% from "_formhelpers.html" import render_field %}
    <form method="POST" action="{{ url_for('.login')}}" role="form">

      {{ form.hidden_tag() }} {{ render_field(form.username, class='form-control') }} {{ render_field(form.password, **{"class":
      "form-control", "aria-described-by": "passwordHelpBlock"}) }}



      <button type="submit" class="btn btn-default">Login</button>

    </form>

  </div>

</div>
{% endblock %}

templates/user/profile.html
{% extends "base.html" %} {% block title %}{{ user.username }} - Profile{% endblock %} {% block header %}
<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">{% endblock %} {% block content %} {% include
"navbar.html" %}

<div class="row">

  <div class="col-md-3">

    <img class="img-thumbnail" src="http://placehold.it/200x200" width="200" height="200" alt="{{ user.username }}">

    <h3 class="profile-fullname">{{ user.first_name }} {{ user.last_name }} </h3>
    <h3 class="profile-username"><a href="{{ url_for('user_app.profile', username=user.username) }}" />@{{ user.username
      }}
      </a></h3>

  </div> <!-- col-md-3 -->

  <div class="col-md-9">

    <div id="friends-toolbar" class="row">

      <div class="btn-toolbar pull-right" role="toolbar" aria-label="friends-toolbar">
        <div class="btn-group" role="group" aria-label="friends-toolbar-buttons">

        </div> <!-- btn-group -->
      </div> <!-- btn-toolbar -->

    </div> <!-- friends-toolbar -->



  </div> <!-- col-md-9 -->

</div>
{% endblock %}

templates/user/register.html
{% extends "base.html" %} {% block title %}Registration{% endblock %} {% block content %} {% include "navbar.html" %}

<div class="row">

  <div class="col-md-offset-3 col-md-6">

    <h3>Registration</h3>

    {% from "_formhelpers.html" import render_field %}
    <!-- . and user_app. do the same in this case -->
    <!--<form method="POST" action="{{ url_for('user_app.register')}}" role="form">-->
    <form method="POST" action="{{ url_for('.register')}}" role="form">

      {{ form.hidden_tag() }} {{ render_field(form.first_name, class='form-control') }} {{ render_field(form.last_name, class='form-control')
      }} {{ render_field(form.username, class='form-control') }} {{ render_field(form.email, class='form-control') }} {{
      render_field(form.password, class='form-control') }} {{ render_field(form.confirm, class='form-control') }}

      <button type="submit" class="btn btn-default">Register</button>

    </form>

  </div>

</div>
{% endblock %}